[tool.black]
line-length = 120
preview = true

[tool.isort]
profile = "black"
known_local_folder = "eolearn"
known_first_party = ["sentinelhub"]
sections = ["FUTURE","STDLIB","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]

[tool.pytest.ini_options]
markers = [
    "sh_integration: marks integration tests with Sentinel Hub service"
]
