[tool.black]
line-length = 120
preview = true

[tool.isort]
profile = "black"
known_first_party = "sentinelhub"
known_absolute = "eolearn"
sections = ["FUTURE","STDLIB","THIRDPARTY","FIRSTPARTY","ABSOLUTE","LOCALFOLDER"]
line_length = 120

[tool.pylint.format]
max-line-length = 120

[tool.pylint.messages_control]
disable = [
    "no-member",
    "arguments-differ",
    "assignment-from-no-return",
    "unsubscriptable-object",
    "invalid-unary-operand-type",
    "unspecified-encoding",
    "unnecessary-ellipsis"
]

[tool.pylint.design]
max-args = 15
max-branches = 15
max-attributes = 20
max-locals = 20
min-public-methods = 0

[tool.pylint.similarities]
min-similarity-lines = 5

[tool.pylint.classes]
valid-metaclass-classmethod-first-arg = "mcs"

[tool.pylint.exceptions]
overgeneral-exceptions = "Exception"

[tool.pylint.refactoring]
max-nested-blocks = 7

[tool.pytest.ini_options]
markers = [
    "sh_integration: marks integration tests with Sentinel Hub service"
]

[tool.coverage.run]
source = [
    "core",
    "coregistration",
    "features",
    "geometry",
    "io",
    "mask",
    "ml_tools",
    "visualization"
]

[tool.coverage.report]
omit = [
    "*/setup.py",
    "*/tests/*",
    "*/__init__.py"
]

[tool.nbqa.addopts]
flake8 = [
    "--extend-ignore=E402"
]

[tool.nbqa.exclude]
flake8 = "examples/core/CoreOverview.ipynb"

[tool.mypy]
follow_imports = "normal"
ignore_missing_imports = true
show_column_numbers = true
show_error_codes = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
# disallow_untyped_defs = true
# disallow_untyped_decorators = true
warn_unreachable = true
strict_equality = true
