"""
Tests for `EOPatch` visualizations

Credits:
Copyright (c) 2017-2022 Matej Aleksandrov, Matej Batič, Grega Milčinski, Domagoj Korais, Matic Lubej (Sinergise)
Copyright (c) 2017-2022 Žiga Lukšič, Devis Peressutti, Nejc Vesel, Jovan Višnjić, Anže Zupanc (Sinergise)

This source code is licensed under the MIT license found in the LICENSE
file in the root directory of this source tree.
"""
import os

import pytest
import numpy as np

from eolearn.core import EOPatch, FeatureType
from eolearn.visualization import PlotConfig


@pytest.fixture(name="eopatch")
def eopatch_fixture():
    path = os.path.join(os.path.dirname(os.path.realpath(__file__)), "..", "..", "..", "example_data", "TestEOPatch")
    return EOPatch.load(path)


@pytest.mark.parametrize(
    "feature, params",
    [
        ((FeatureType.DATA, "BANDS-S2-L1C"), {"rgb": [3, 2, 1]}),
        ((FeatureType.MASK, "CLM"), {}),
        ((FeatureType.MASK, "IS_VALID"), {}),
        ((FeatureType.SCALAR, "CLOUD_COVERAGE"), {}),
        ((FeatureType.LABEL, "IS_CLOUDLESS"), {}),
        ((FeatureType.LABEL, "RANDOM_DIGIT"), {}),
        ((FeatureType.VECTOR, "CLM_VECTOR"), {}),
        ((FeatureType.DATA_TIMELESS, "DEM"), {}),
        ((FeatureType.MASK_TIMELESS, "RANDOM_UINT8"), {}),
        ((FeatureType.SCALAR_TIMELESS, "LULC_PERCENTAGE"), {}),
        ((FeatureType.LABEL_TIMELESS, "LULC_COUNTS"), {}),
        ((FeatureType.VECTOR_TIMELESS, "LULC"), {}),
        (FeatureType.BBOX, {}),
    ],
)
def test_eopatch_plot(eopatch, feature, params):
    """A simple test of EOPatch plotting for different features."""
    # We reduce width and height otherwise running matplotlib.pyplot.subplots in combination with pytest would
    # kill the Python kernel.
    config = PlotConfig(subplot_width=1, subplot_height=1)

    axes = eopatch.plot(feature, config=config, **params)
    axes = axes.flatten()

    assert isinstance(axes, np.ndarray)
    for item in axes:
        # AxesSubplot class seems to be generated by matplotlib factory and can't be imported
        assert item.__class__.__name__ == "AxesSubplot"
