name: trigger

on:
  release:
    types:
      - published

jobs:
  trigger:
    image: alpine
    script:
      - apk add --no-cache curl
      - >
        curl -X POST --fail \
          -F token=${{ secrets.GITLAB_PIPELINE_TRIGGER_TOKEN }} \
          -F ref=main \
          -F variables[CUSTOM_RUN_TAG]=auto \
          -F variables[LAYER_NAME]=dotai-eo \
          https://git.sinergise.com/api/v4/projects/1031/trigger/pipeline
